# Generated by Django 3.0.3 on 2020-04-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_company', models.CharField(max_length=200)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_prefecture', models.CharField(max_length=50)),
                ('customer_addr', models.CharField(max_length=400)),
                ('create_dt', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
