# Generated by Django 3.0.3 on 2020-04-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=200, verbose_name='医療機関名')),
                ('zip_code', models.CharField(blank=True, max_length=8, verbose_name='zip code')),
                ('prefecture', models.CharField(blank=True, max_length=40, verbose_name='Prefecture')),
                ('address1', models.CharField(blank=True, max_length=40, verbose_name='Address1')),
                ('address2', models.CharField(blank=True, max_length=40, verbose_name='Address2')),
            ],
        ),
        migrations.CreateModel(
            name='PrefectureMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Prefecture')),
            ],
        ),
    ]
