# Generated by Django 3.0.3 on 2020-04-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emaskjp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='address1',
            field=models.CharField(max_length=40, verbose_name='市区町村番地'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='address2',
            field=models.CharField(blank=True, max_length=40, verbose_name='建物名'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='prefecture',
            field=models.CharField(max_length=40, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='郵便番号'),
        ),
    ]
