# Generated by Django 3.0.3 on 2020-04-23 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emaskjp', '0003_auto_20200423_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='医療機関名'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='zip_code'),
        ),
    ]
