# Generated by Django 3.0.3 on 2020-04-24 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emaskjp', '0004_auto_20200423_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField()),
                ('demand_qty', models.DecimalField(decimal_places=6, max_digits=16)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emaskjp.Entity')),
            ],
            options={
                'unique_together': {('entity', 'begin_date')},
            },
        ),
    ]
