# Generated by Django 3.0.3 on 2020-04-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emaskjp', '0005_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='begin_date_display',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='年/月'),
        ),
    ]
