# Generated by Django 3.0.3 on 2020-04-27 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emaskjp', '0007_request_supplier_suppliercontact_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='zip_code'),
        ),
        migrations.AlterField(
            model_name='request',
            name='last_calculated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 26, 21, 14, 39, 142776), null=True),
        ),
    ]
